@startuml   

actor Test02
activate Test02

create participant "unaCorbeta :Corbeta" as corbeta
Test02 -> corbeta : <<create>> Corbeta()
create participant "unEscudoSimple: Simple" as escudoSimple
activate corbeta
corbeta -> escudoSimple : <<create>> Simple()
create participant "ataqueMisiles :Misil" as ataqueCorbeta
corbeta -> ataqueCorbeta : <<create>> Misil(cantidad=3 ,puntajePorUnidad=10)

deactivate corbeta

create participant "unDestructor : Destructor" as destructor
Test02 -> destructor : <<create>> Destructor()

activate destructor

create participant "ataqueMisiles2 :Misil" as ataqueDestructor

destructor -> ataqueDestructor : <<create>> Misil(cantidad=5,puntajePorUnidad=1)

create participant "unEscudoFenix :Fenix" as escudoFenix

destructor -> escudoFenix : <<create>> Fenix()


deactivate destructor


create participant "unAcorazado: Acorazado" as acorazado
Test02 -> acorazado : <<create>> Acorazado()
create participant "bombaNeutron : BombaNeutron" as bomba
activate acorazado
acorazado -> bomba : <<create>> Misil(cantArma = 10 , puntosPorArma = 5)


create participant "torretaIonica : TorretaIonica" as torreta
acorazado -> torreta : <<create>> TorretaIonica(bombaNeutron)




create participant "escudoIonico : Ionico" as escudoIonico
acorazado -> escudoIonico : <<create>> Ionico(torretaIonica)
deactivate acorazado


create participant "unaFlota: Flota" as flota 
Test02 -> flota : <<create>> Flota([unAcorazado,unaCorbeta,unDestructor])





@enduml    