@startuml   


actor Test01
activate Test01

create participant "unAcorazado :Acorazado" as acorazado

Test01 -> acorazado : <<create>> Acorazado()

create participant "bombaNeutron : BombaNeutron" as bomba
activate acorazado
acorazado -> bomba : <<create>> Misil(cantArma = 10 , puntosPorArma = 5)


create participant "torretaIonica : TorretaIonica" as torreta
acorazado -> torreta : <<create>> TorretaIonica(bombaNeutron)




create participant "escudoIonico : Ionico" as escudoIonico
acorazado -> escudoIonico : <<create>> Ionico(torretaIonica)
deactivate acorazado

Test01 -> acorazado : disparar()
activate acorazado
acorazado -> torreta : disparar()
activate torreta
torreta -> bomba : disparar()
activate bomba 
deactivate bomba
deactivate torreta
deactivate acorazado


Test01 -> acorazado : disparar()
activate acorazado
acorazado -> torreta : disparar()
activate torreta
torreta -> bomba : disparar()
activate bomba 
deactivate bomba
deactivate torreta
deactivate acorazado

note right
    "metodo dentro de la clase 
    TorretaIonica"

    disparar(){
        this.bombasGastadas += 1
        bombaNeutron.disparar() ;
    }

    "metodo dentro de la 
    clase Bomba"

    disparar(){
        this.cantidadBombas -=1
    }

end note




Test01 -> acorazado : calcularPuntaje()
activate acorazado
acorazado -> torreta : calcularPuntaje()

activate torreta
torreta -> bomba : bombasNecesarias()
activate bomba
bomba --> torreta : false
torreta -> bomba : calcularPuntaje()
bomba --> torreta : puntajeBomba = cantArma * puntosPorArma = 40
deactivate bomba
torreta --> acorazado : puntajeAtaque = puntajeBomba + puntajeTorreta  = 130 
deactivate torreta

note right

"metodo en torreta"

    calcularPuntaje(){
        if(bombaNeutron.bombasNecesarias){
            return puntosTorreta + (bombaNeutron.calcularPuntaje())
        }else{
            return (puntosTorreta-bombasGastadas*10) + bombaNeutron.calcularPuntaje()
        }
    }
end note





acorazado -> escudoIonico : calcularPuntaje()
activate escudoIonico
escudoIonico -> torreta : calcularPuntaje()

activate torreta
torreta -> bomba : bombasNecesarias()
activate bomba
bomba --> torreta : false
torreta -> bomba : calcularPuntaje()
bomba --> torreta : puntajeBomba = cantArma * puntosPorArma = 40
deactivate bomba
torreta --> escudoIonico : puntajeAtaque = puntajeBomba + puntajeTorreta  = 130 
deactivate torreta



escudoIonico --> acorazado : puntajeEscudo = puntajeAtaque = 130
deactivate escudoIonico

note right
    "El puntaje escudo multiplica x2 
    el puntaje actual de ataque , 
    por ende es lo mismo decir que 
    suma puntaje ataque"

    calcularPuntaje(){
    
        return torretaIonica.calcularPuntaje();
    
    }


end note

acorazado --> Test01 : puntajeAcorazado = puntajeAtaque + puntajeEscudo = 130 + 130
deactivate Test01










@enduml  

