@startuml

class Flota{

    +Flota(List<Nave>)
    +calcularPuntaje() : int
}



class Acorazado{

    +Acorazado()
    +calcularPuntaje() :int 
    +disparar()
}

class Corbeta {

    +Corbeta()
    +calcularPuntaje() :int 
    +disparar()


}

class Destructor {


    +Destructor()
    +calcularPuntaje() :int 
    +disparar()

}

abstract class Nave{

    +calcularPuntaje() :int 
    +disparar()
}

abstract class SistemaDeAtaque{
    #cantidadArma : int
    #puntosPorArma : int

    +calcularPuntaje() : int
    +disparar()
}

class BombaNeutron{

    +BombaNeutron(cantArma : int , puntosPorArma : int)
    +bombasNecesarias() : boolean
    +calcularPuntaje() : int
    +disparar() 


}

class Misil{

    +Misil(cantArma : int , puntosPorArma : int)
    +calcularPuntaje() : int
    +disparar()

}

class TorretaIonica{
    -bombasGastadas :int
    -bombas : BombaNeutron

    +TorretaIonica(bombas : BombaNeutron)
    +calcularPuntaje() : int
    +disparar()

}





abstract class Escudo{

    +calcularPuntaje() : int
}

class Ionico{
    -unSistemaDeAtaque : SistemaDeAtaque

    +Ionico(ataque :SistemaDeAtaque)
    +calcularPuntaje() : int
}

class Fenix{
    -dañoRecibido :int

    +calcularPuntaje() : int
    +recibirDaño();

}

class Simple{
    -dañoRecibido :int
    
    +calcularPuntaje() : int
    +recibirDaño();

}

interface Dañable{
    recibirDaño();
}

TorretaIonica --|> SistemaDeAtaque
BombaNeutron --|> SistemaDeAtaque
Misil --|> SistemaDeAtaque
Escudo --|> Ionico
Escudo --|> Fenix
Escudo --|> Simple

Destructor --|> Nave
Corbeta --|> Nave
Acorazado --|> Nave

Nave "1" o-- "*" SistemaDeAtaque
Nave -> Escudo

Flota "1" o-- "*" Nave

Fenix ..|> Dañable
Simple ..|> Dañable



@enduml