@startuml

'calcular energia de chancho volador despues de 2 aleteos'


actor test01
activate test01

create participant "unChancho : ChanchoVolador" as chancho1
test01 -> chancho1 : <<create>> ChanchoVolador()
create participant "habilidadVolar : Volar" as volarChancho
activate chancho1
chancho1 -> volarChancho : <<create>> Volar(costo = 8 , veces =10)
deactivate chancho1


   
test01 -> chancho1 : usarHabilidad(volar,2)
activate chancho1
chancho1 -> volarChancho: accion(2)
activate volarChancho
test01 -> chancho1 : calcularEnergia()
chancho1 -> volarChancho : calcularEnergia()
volarChancho --> chancho1 : energiaChancho = movimientoDisponible * costo
deactivate volarChancho
chancho1 --> test01 : energiaChancho
deactivate chancho1
deactivate test01







@enduml