@startuml

'calcular energia de chancho volador despues de 2 aleteos'


actor main
activate main

create participant "unChancho:ChanchoVolador" as chancho
main -> chancho : <<create>> ChanchoVolador()
create participant "habilidadVolar : Volar" as volarChancho
chancho -> volarChancho : <<create>> Volar(costo=8,veces=10)

create participant "unGanso : Ganso" as ganso
main -> ganso : <<create>>Ganso()
create participant "habilidadVolar2 : Volar" as volarGanso
ganso -> volarGanso : <<create>> Volar(costo=4,veces=3)
create participant "habilidadNadar : Nadar" as nadarGanso
ganso -> nadarGanso : <<create>> Nadar(costo=2,veces=4)

create participant "unPato : Pato" as pato
main -> pato : <<create>> Pato()
create participant "habilidadNadar2 :Nadar" as nadarPato
pato -> nadarPato : <<create>> Nadar(costo=5,veces=3)

create participant "animales: List<Animal>" as animales
main -> animales : <<create>> List<Animal>()
activate animales
main -> animales : add(unChancho)
main ->animales : add(unGanso)
main -> animales : add(unPato)
deactivate animales

create participant "unaGranja : GranjaDeOrson" as granja
main -> granja : <<create>>GranjaDeOrson(animales)
main -> granja : calcularEnergia()
activate granja

granja -> chancho : calcularEnergia()
activate chancho
chancho -> volarChancho : calcularEnergia()
activate volarChancho
volarChancho --> chancho : energiaChancho
deactivate volarChancho
chancho --> granja : energiaChancho
deactivate chancho

granja -> ganso : calcularEnergia()
activate ganso
ganso -> volarGanso : calcularEnergia()
activate volarGanso
volarGanso --> ganso : energiaVuelo
deactivate volarGanso
ganso -> nadarGanso : calcularEnergia()
activate nadarGanso
nadarGanso --> ganso : energiaNadar
deactivate nadarGanso
ganso --> granja : energiaNadar + energiaVuelo = energiaGanso
deactivate ganso

granja -> pato : calcularEnergia()
activate pato  
pato -> nadarPato : calcularEnergia()
activate nadarPato
nadarPato --> pato : energiaPato
deactivate nadarPato
pato --> granja : energiaPato
deactivate pato

granja --> main : (energiaChancho + energiaGanso + energiaPato) + 10%
deactivate main









@enduml