@startuml

'calcular energia de chancho volador despues de 2 aleteos'


actor test02
activate test02

create participant "unChancho:ChanchoVolador" as chancho
test02 -> chancho : <<create>> ChanchoVolador()
create participant "habilidadVolar : Volar" as volarChancho
chancho -> volarChancho : <<create>> Volar(costo=8,acciones=10)


create participant "unGanso : Ganso" as ganso
test02 -> ganso : <<create>>Ganso()
create participant "habilidadVolar2 : Volar" as volarGanso
ganso -> volarGanso : <<create>> Volar(costo=4,acciones=3)
create participant "habilidadNadar : Nadar" as nadarGanso
ganso -> nadarGanso : <<create>> Nadar(costo=2,acciones=4)

note right
    el ganso tiene un arreglo de habilidades
    
    habilidades = [Volar ,Nadar]

    cada habilidad tiene un costo por movimiento 
    y una cantidad de movimientos
end note

create participant "unPato : Pato" as pato
test02 -> pato : <<create>> Pato()
create participant "habilidadNadar2 :Nadar" as nadarPato
pato -> nadarPato : <<create>> Nadar(costo=5,acciones=3)


create participant "unaGranja : GranjaDeOrson" as granja
test02 -> granja : <<create>>GranjaDeOrson([unGanso,unPato,unChancho])

deactivate test02


@enduml